---
output:
  pdf_document: default
  html_document: default
---
# Thinking about skills/objectives

The idea is to divide along two directions:

1. The kind of action the student should be able to perform.
2. The topic to which (1) applies


## Basic categories of action

- Graphical interpretation: **Gi**
- Graphics construction: **Gc**
- Symbolic computation: **Sc**
- Notation reading: **Nr**
- Numeric computation: **Co**mputer
- Hand computation: **Ha**nd
- Establish consistency: **Co**nfirm
- Conceptual relationship: **Re**
- Recognize and use vocabulary appropriately: **Vo**


# Topics

## Functions **Fun**

100. Notation for function creation: inputs, output, parameters, $\equiv$, `makeFun()`
#. Notation conventions: scalars vs functions
#. Evaluation of function
    a. from formula
    b. on computer
#. Shapes of functions
    a. slope, concavity, curvature, discontinuity, extrema, monotonic, inflection point
#. Pattern-book functions
#. Domain and range
#. Parameters (basic modeling functions)
    a. parameters with `makeFun()
#. Input centering e.g $[x - x_0]$
#. Input scaling 
#. Slope at a point
    a. Directional slope at a point
    b. Working with contours
#. Piecewise functions 
#. Vector-valued functions (e.g. gradient)
#. Table as a function, graph as a function [be able to evaluate, find slope, accumulate]
#. Assembling functions
    a. linear combination (coefficients, scalar multipliers)
    a. composition
    a. product
#. Partial evaluation (e.g. in anti-derivatives or taking a slice)
#. Functions from data
    a. Splines and other interpolants
        i. constructing by software
        i. when is smoothness necessary (cubic spline) or not wanted (Bezier)
    a. Fitting by eye for basic modeling functions
    a. Least squares fitting
    a. Evaluate function from a table (including multivariate)
#. Exponentials
    a. Interpretation as half-life, doubling-time
    a. Complex exponentials and interpretation as damped (or growing) sinusoid
        i. determine frequency from eigenvalues
#. Logarithms
    a. Graphical uses
    #. Graphics for functions
    a. slice plot
    a. contour plot
    a. surface plot
    a. vector field
    a. graphical domain
    a. paths and constraints
#. Parametric description of path as a set of functions of $t$.    
    
## Optimization **Opt**

650. Vocabulary: argmax vs max
#. Objective function
#. Incommensurate objectives
#. Constraints
    a. Active or not
    b. Equality and inequality
    c. Shadow price (Lagrange multiplier)
    d. constraint functions
    e. parallel gradients for constraint function and objective function at argmax
#. Numerical techniques 
#. Derivatives and critical points
#. Gradient vector points uphill, not necessarily toward optimum
#. Gradient ascent/descent algorithm
#. Find argmax/min from gradient field
#. Find argmax/min from contour plot

    
## Data **Dat**

200. Organization of a data frame
#. Point plot
#. Estimating function parameters (linear and nonlinear for basic modeling functions)
    a. straight-line
    b. exponential
    c. sinusoid
    d. gaussian and sigmoid
    e. distinguish between power-law and exponential
    f. log axes
#. Function as a table
#. Residual between response var and output of a model function

## Dimension analysis **Dim**

300. Fundamental dimensions
#. Compound dimensions and dimensional arithmetic
    a. invalid operations on dimensional quantities
    b. Know dimension of basic physical quantities (acceleration, force, energy, power, pressure, area, volume, work=force x distance, energy = power x time, power = force x velocity)
#. Determine dimensional consistency
#. Unit conversion and flavors of 1
#. Dimension of derivatives and anti-derivatives
#. Power-law functions

## Calculus operations **Cal**

400. Vocabulary
#. With-respect-to input
#. Notations: $\partial_t x$, $\dot{x}$, $\frac{dx}{dt}$, $\frac{\partial x}{\partial t}$
#. Accumulation **Acc**
    a. Symbolic anti-differentation
        i. pattern book functions
        i. basic modeling functions (simple chain rule)
    a. Appropriate notation
    a. Constant of integration (also form from `antiD()`)
    a. Definite integral, net change
    a. Numerical integration and anti-differentiation
    a. "Area under a curve" and why it's signed area
    a. Fundamental theorem
        i. relationship between differentiation and anti-differentiation
        i. confirm anti-derivative by differentiation
    a. Estimate from graph
    a. anti-differentiation: output is a function
    a. integration: output is a quantity
    a. `antiD()` in R and how to evaluate it for definite integral 
    a. calculating work by integrating force over distance
    a. calculate energy by integrating power over time
    a. calculate center of mass, centroid, moment of inertia
    a. find probability that random variable is in a range
    a. discounting
    
#. Differentiation **Dif**
    a. Symbolic differentiation
        i. pattern book functions
        i. basic modeling functions (simple chain rule)
        i. chain rule
        i. product rule
        i. sum rule
        i. by computer
    b. Numerical differentiation
    c. Second and higher-order derivatives
    d. Partial derivatives
        i. first order
        i. second-order, including mixed partials
    e. Gradient vector
        i. relationship to contours
    f. Order of smoothness
    g. Relationship to velocity and acceleration
    h. output is a function
    i. identifying monotonicity, concavity, curvature, critical points
    j. tangents: line, circle, polynomial
    
#. Argmax finding

## Other operations

500. Zero finding (and inversion, solution)
#. Find zeros of linear functions by hand
#. Simultaneous zeros (e.g. crossings of nullclines)
#. Iteration
    a. improvement
    b. Newton method

## Calculus theory **Theory**

600. Vocabulary
#. Slope function
#. Finite-difference approximation to derivative
    a. limit definition of a derivative
#. Euler accumulation
#. Value/Existence for a limit
#. Taylor polynomials
    a. Pick center $x_0$
    b. Memorize for sin(), cos(), exp()
    c. Compute error for a given input, characterize error as a function of $x - x_0$.
#. Local linear approximation 
#. Differentials
#. Instantaneous vs average rate of change

## Approximation **Approx**

700. Vocabulary
#. Polynomials
    a. linear, interaction, quadratic terms
#. Linearization
#. Low-order polynomial approximation

## Linear algebra **Lal**

800. Vocabulary
#. Acceleration, position, momentum, velocity are vector quantities
#. Vectors are rootless, have just direction and magnitude
#. Vector operations (add, scale, dot product)
#. Matrices
#. Target problem
#. Eigenvectors and eigenvalues
#. Subspace
    a. Is a vector a member of a subspace? (numerically)
    b. Projection
    c. Residual

## Dynamics **Dyn**

900. Dynamical system as set of first-order differential equations
#. Numerical integration from initial condition
#. Symbolic integration: 
    a. first-order linear
    b. eigenvalues, characteristic values and stability
    c. exponential ansatz
    d. linear combinations of solutions are solutions in linear systems
#. Flows
#. Trajectories
#. Time series
#. Nullclines 
#. Unlimited and limited growth models, logistic growth
#. Bifurcation (appearance and disappearance of fixed points in 1-D)
#. Classic models: predator-prey, SIR
#. Force-balance and equivalence to pair of first-order differential equations
#. Identify physical quantities (resistance, restoring force) in force-balance 

## Probability **Prob**

1000. meaning of random variable, event
#. probability density vs relative density
#. normalization of relative density
#. expected value, variance, standard deviation,

## Computer **Comp**

1100. Translate math formula into R formula and vice versa
#. Construct a function with parameters
    a. set default values for parameters
#. Graphics layers
    
## Modeling concepts **Mod**

1200. Different models for different purposes
#. Frameworks:
    a. low-order polynomials
        i. which terms are appropriate
        i. constructing from first principles
        i. constructing from data
        i. limitations for modeling (dog chasing squirrel)
    a. differential equations
#. Modeling cycle
    
